# Generated by Django 3.0.7 on 2020-09-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Running'), ('W', 'Waiting on Parts'), ('D', 'Down for Repair')], default='R', max_length=1, verbose_name='Machine Status')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('downtime', models.DateTimeField(blank=True, null=True)),
                ('machine_name', models.CharField(max_length=10, verbose_name='Machine Name')),
                ('machine_row', models.CharField(max_length=10, verbose_name='Machine Row')),
                ('machine_e2name', models.CharField(max_length=10, verbose_name='E2 Machine Name')),
            ],
            options={
                'verbose_name': 'Machine Status',
                'verbose_name_plural': 'Machine Status',
            },
        ),
    ]
