# Generated by Django 3.0.7 on 2020-09-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0002_auto_20200921_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinestatus',
            name='downtime',
        ),
        migrations.AlterField(
            model_name='machinestatus',
            name='machine_e2name',
            field=models.CharField(max_length=10, verbose_name='Work Station Name'),
        ),
    ]
