# Generated by Django 3.0.7 on 2020-09-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0004_auto_20200922_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestatus',
            name='downtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
