# Generated by Django 3.0.7 on 2020-09-23 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0006_auto_20200922_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('1', 'General Note'), ('2', 'Crash'), ('3', 'Preventive Maintenance'), ('4', 'Repair')], max_length=2, verbose_name='Reason for Record')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('note', models.TextField(verbose_name='Note')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmaint.MachineStatus', verbose_name='Machine Number')),
            ],
        ),
    ]
