# Generated by Django 3.0.7 on 2020-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0007_permanentrecords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permanentrecords',
            options={'ordering': ['-date'], 'verbose_name': 'Permanent Machine Records', 'verbose_name_plural': 'Permanent Machine Records'},
        ),
        migrations.AlterField(
            model_name='permanentrecords',
            name='date',
            field=models.TimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
