# Generated by Django 3.0.7 on 2020-09-23 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0008_auto_20200923_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentrecords',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permanentrecords',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
