# Generated by Django 3.0.7 on 2020-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0010_machinedownreports'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinedownreports',
            options={'ordering': ['-starttime', '-endtime'], 'verbose_name': 'Machine Down Reports', 'verbose_name_plural': 'Machine Down Reports'},
        ),
        migrations.AddField(
            model_name='machinedownreports',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
