# Generated by Django 3.0.7 on 2020-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0012_auto_20201008_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinestatus',
            options={'ordering': ['status', 'machine_name'], 'permissions': [('pso_indicating_fixture', "PSO's Indicating the fixture status"), ('pm_preventative_maintenance', 'Can put machine into preventative maintenance status')], 'verbose_name': 'Machine Status', 'verbose_name_plural': 'Machine Status'},
        ),
        migrations.AlterField(
            model_name='machinestatus',
            name='notes',
            field=models.CharField(blank=True, help_text='150 Character Limit.', max_length=150, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='machinestatus',
            name='status',
            field=models.CharField(choices=[('4', 'Running'), ('3', 'Fixture Indication'), ('2', 'Down for PM'), ('1', 'Down for Repair')], default='3', max_length=1, verbose_name='Machine Status'),
        ),
        migrations.AlterField(
            model_name='permanentrecords',
            name='reason',
            field=models.CharField(choices=[('1', 'General Note'), ('2', 'Crash'), ('3', 'Preventive Maintenance'), ('4', 'Repair'), ('5', 'Auto-Generated Note'), ('6', 'Contact'), ('7', 'Fixture Indication')], max_length=2, verbose_name='Reason for Record'),
        ),
    ]
