# Generated by Django 3.0.7 on 2020-11-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmaint', '0015_auto_20201019_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permanentrecords',
            options={'verbose_name': 'Repair Action Records', 'verbose_name_plural': 'Repair Actions Records'},
        ),
        migrations.AlterField(
            model_name='machinedownreports',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='mmaint.MachineStatus', verbose_name='Machine Number'),
        ),
        migrations.AlterField(
            model_name='permanentrecords',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_names', to='mmaint.MachineStatus', verbose_name='Machine Number'),
        ),
    ]
